const char *vertexDeferredAmbientShader =
        "#version 330 core\n"
        "\n"
        "layout (location = 0) in vec3 aPos;\n"
        "layout (location = 1) in vec2 aTexCoords;\n"
        "\n"
        "out vec3 EyeDirection;\n"
        "out vec2 TexCoords;\n"
        "\n"
        "layout (std140) uniform shader_data\n"
        "{ \n"
        "    mat4 view_projection;\n"
        "    mat4 prev_view_projection;\n"
        "    mat4 projection;\n"
        "    mat4 view;\n"
        "    mat4 inverse_view;\n"
        "    mat4 inverse_projection;\n"
        "    vec2 half_size_near_plane;\n"
        "};\n"
        "\n"
        "void main()\n"
        "{\n"
        "   TexCoords = aTexCoords;\n"
        "   EyeDirection = vec3((2.0 * half_size_near_plane * aTexCoords) - half_size_near_plane , -1.0);\n"
        "   gl_Position = vec4(aPos.xy, 0, 1);\n"
        "}";

const char *fragmentDeferredAmbientShader =
        "#version 330 core\n"
        "//Fragment shader\n"
        "layout (location = 0) out vec3 FragColor;\n"
        "in vec3 EyeDirection;\n"
        "in vec2 TexCoords;\n"
        "\n"
        "layout (std140) uniform shader_data\n"
        "{ \n"
        "    mat4 view_projection;\n"
        "    mat4 prev_view_projection;\n"
        "    mat4 projection;\n"
        "    mat4 view;\n"
        "    mat4 inverse_view;\n"
        "    mat4 inverse_projection;\n"
        "    vec2 half_size_near_plane;\n"
        "};\n"
        "\n"
        "uniform sampler2D gDiffuseSpecular;\n"
        "uniform sampler2D gNormal;\n"
        "uniform sampler2D gDepth;\n"
        "\n"
        "vec4 CalcViewPosFromWindow(in float windowZ, in vec3 eyeDirection, in mat4 projMatrix)\n"
        "{\n"
        "  float ndcZ = 2.0 * windowZ - 1;\n"
        "  float viewZ = -projMatrix[3][2] / ((projMatrix[2][3] * ndcZ) - projMatrix[2][2]);\n"
        "  return vec4(EyeDirection * viewZ, 1);\n"
        "}\n"
        "\n"
        "void main()\n"
        "{\n"
        "  vec4  viewPosition   = CalcViewPosFromWindow(texture(gDepth, TexCoords).x, EyeDirection, projection);\n"
        "  vec3  worldPosition  = (inverse_view*viewPosition).rgb;\n"
        "  vec3  normal         = texture(gNormal, TexCoords).rgb;\n"
        "  vec3  diffuse        = texture(gDiffuseSpecular, TexCoords).rgb;\n"
        "  float specular       = texture(gDiffuseSpecular, TexCoords).a;\n"
        "  \n"
        "  FragColor            = diffuse * 0.1;\n"
        "}";

